---
settings:
  name: E-Series Family
  search: e-series,e-series-santricity,e-series-cli
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione sulla famiglia di prodotti e-Series
    url: "/index.html"
  - title: Note legali
    url: "/legal-notices.html"
