---
settings:
  name: E-Series Family
  search: e-series,e-series-santricity,e-series-cli
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione sulla famiglia di prodotti e-Series
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: Tutti i documenti
    tags: tag_storage_management,tag_data_storage,tag_cli,tag_get_started,tag_SANtricity,
      tag_solution
    class: active
  - title: Inizia subito
    tags: tag_get_started
  - title: Storage dei dati
    tags: tag_data_storage
  - title: Gestione dello storage
    tags: tag_storage_management, tag_SANtricity
  - title: Soluzioni
    tags: tag_solution
  tiles:
  - title: Scopri di più su e-Series
    icon: "./media/groups_line-1.png"
    url: intro-family.html
    summary: Scopri la famiglia di sistemi storage e-Series.
    tags: all, tag_get_started
  - title: Sistemi e-Series
    icon: "./media/system_line.png"
    url: https://docs.netapp.com/us-en/e-series/index.html
    summary: Utilizza i sistemi storage e-Series per supportare i carichi di lavoro
      delle tue applicazioni con un rapido storage a blocchi e un'affidabilità di
      livello Enterprise.
    tags: all, tag_data_storage
  - title: Software SANtricity
    icon: "./media/config_line.png"
    url: https://docs.netapp.com/us-en/e-series-santricity/index.html
    summary: Utilizza il software SANtricity per eseguire il provisioning e la gestione
      dei sistemi storage e-Series da un'interfaccia basata su Web.
    tags: all, tag_storage_management, tag_SANtricity
  - title: Interfaccia della riga di comando
    icon: "./media/cli_line.png"
    url: https://docs.netapp.com/us-en/e-series-cli/index.html
    summary: Utilizzare la CLI per configurare e monitorare i sistemi storage e-Series
      da un prompt del sistema operativo.
    tags: all, tag_storage_management, tag_SANtricity
  - title: API dei servizi Web
    icon: "./media/api.png"
    url: https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html
    summary: Utilizza l'API RESTful per creare e automatizzare i flussi di lavoro
      nei tuoi sistemi storage e-Series nuovi e legacy.
    tags: all, tag_storage_management, tag_SANtricity
  - title: BeeGFS su NetApp con storage e-Series
    icon: "./media/api.png"
    url: https://docs.netapp.com/us-en/beegfs/index.html
    summary: Utilizza BeeGFS su NetApp per creare e implementare un'infrastruttura
      ad alta disponibilità che combina il file system parallelo BeeGFS con i sistemi
      storage NetApp EF600.
    tags: all, tag_solution
